### ISSUE TITLE
Sürekli Tekrarlayan Nesneler ve Haritalar Nasıl Oluşturulur?

### ISSUE THREAD

**Issue by 198168Cf189168Cf** [sezginkipel/Oyun-Programlama-Dersi#5]
platformu sonsuz uzatmayı nasıl yapabilirim ?

**Comment by sezginkipel** [comment]
Sonsuz bir platform yaratmak ya da platforma sonsuz hissi vermek için yapabileceğin bazı çözümler;

1-) Instantiate ile platformu klonlama.

2-) Karakteri sabit tutmak, oyun nesnelerini karaktere doğru hareket ettirmek ve oyun nesnelerinin birer örneğini yaratmak.


Klonlama işlemi için örnek kod:

`Instantiate(klonlanacakNesnePrebaf, klonlananNesneKonumu(x, y, z olarak), Quaternion.identity);`

**Comment by sezginkipel** [comment]
Sonsuz bir platform yaratmak ya da platforma sonsuz hissi vermek için yapabileceğin bazı çözümler;

1-) Instantiate ile platformu klonlama.

2-) Karakteri sabit tutmak, oyun nesnelerini karaktere doğru hareket ettirmek ve oyun nesnelerinin birer örneğini yaratmak.


Klonlama işlemi için örnek kod:

`Instantiate(klonlanacakNesnePrebaf, klonlananNesneKonumu, Quaternion.identity);`

**Comment by sezginkipel** [comment]
Bu konseptleri de içeren örnek bir proje hazırladım.

https://github.com/sezginkipel/Oyun-Programlama-Dersi/discussions/6
